'use strict';

/**
 * @fileOverview exports webpack development config
 * generated by webpack-injector
 */

// ----------------------------------------
// Imports
// ----------------------------------------

const injector = require('./index');

// ----------------------------------------
// Private
// ----------------------------------------

// ----------------------------------------
// Public
// ----------------------------------------

injector
	.mode('development')
	.hot(true)
	.sourcemaps(true)
	.publicPath('/dist/js/')
	.js('./src/js/app.js', './dist/js/bundle-app.js')
	.sass('./src/sass/common.scss', './dist/css/bundle-common.css')
	.modernizrrc('.modernizrrc')
	.bLENME('custom-jquery-methods')
	.bLENME('swiper')
	.externals('jquery', 'jQuery');

console.log(injector.exportWebpackConfig());

// ----------------------------------------
// Exports
// ----------------------------------------

module.exports = injector.exportWebpackConfig();
